// This file was generated by Version2Header
// Tue Feb 12 00:24:13 EET 2019


#ifndef GIT_HASH
#define GIT_HASH "086b908e17b82a7705d7e6935571fdc29fd55786"
#endif


#ifndef VCS_VERSION
#define VCS_VERSION "16768"
#endif
